// <auto-generated />
using System;
using DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(PostgreDbContext))]
    [Migration("20220605190952_Deneme")]
    partial class Deneme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcademicJournalEditor", b =>
                {
                    b.Property<Guid>("AcademicJournalsId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_journals_id");

                    b.Property<Guid>("EditorsId")
                        .HasColumnType("uuid")
                        .HasColumnName("editors_id");

                    b.HasKey("AcademicJournalsId", "EditorsId")
                        .HasName("pk_academic_journal_editor");

                    b.HasIndex("EditorsId")
                        .HasDatabaseName("ix_academic_journal_editor_editors_id");

                    b.ToTable("academic_journal_editor", (string)null);
                });

            modelBuilder.Entity("AcademicJournalResearcher", b =>
                {
                    b.Property<Guid>("AcademicJournalsId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_journals_id");

                    b.Property<Guid>("ResearchersId")
                        .HasColumnType("uuid")
                        .HasColumnName("researchers_id");

                    b.HasKey("AcademicJournalsId", "ResearchersId")
                        .HasName("pk_academic_journal_researcher");

                    b.HasIndex("ResearchersId")
                        .HasDatabaseName("ix_academic_journal_researcher_researchers_id");

                    b.ToTable("academic_journal_researcher", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.AcademicJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AJNumber")
                        .HasColumnType("integer")
                        .HasColumnName("aj_number");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("DateOfYear")
                        .HasColumnType("integer")
                        .HasColumnName("date_of_year");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DimensionsId")
                        .HasColumnType("uuid")
                        .HasColumnName("dimensions_id");

                    b.Property<Guid?>("EMaterialFilesId")
                        .HasColumnType("uuid")
                        .HasColumnName("e_material_files_id");

                    b.Property<Guid>("EditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_id");

                    b.Property<int>("EndPageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("end_page_number");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_id");

                    b.Property<Guid>("ResearcherId")
                        .HasColumnType("uuid")
                        .HasColumnName("researcher_id");

                    b.Property<byte>("SecretLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("secret_level");

                    b.Property<int>("StartPageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("start_page_number");

                    b.Property<byte>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<Guid>("TechnicalPlaceholdersId")
                        .HasColumnType("uuid")
                        .HasColumnName("technical_placeholders_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_academic_journals");

                    b.ToTable("academic_journals", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_name");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("GeoLocation")
                        .HasColumnType("text")
                        .HasColumnName("geo_location");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_addresses_city_id");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_addresses_country_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AcademicJournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_journal_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("AcademicJournalId")
                        .HasDatabaseName("ix_categories_academic_journal_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Communication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommunicationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("communication_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("fax_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("web_site");

                    b.HasKey("Id")
                        .HasName("pk_communications");

                    b.ToTable("communications", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Composer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NamePreAttachment")
                        .HasColumnType("text")
                        .HasColumnName("name_pre_attachment");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id")
                        .HasName("pk_composers");

                    b.ToTable("composers", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Consultant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NamePreAttachment")
                        .HasColumnType("text")
                        .HasColumnName("name_pre_attachment");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id")
                        .HasName("pk_consultants");

                    b.ToTable("consultants", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.CoverCap", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("BookSkinType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book_skin_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_cover_caps");

                    b.ToTable("cover_caps", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Dimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcademicJournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_journal_id");

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<double>("Length")
                        .HasColumnType("double precision")
                        .HasColumnName("length");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_dimensions");

                    b.HasIndex("AcademicJournalId")
                        .HasDatabaseName("ix_dimensions_academic_journal_id");

                    b.ToTable("dimensions", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id")
                        .HasName("pk_directors");

                    b.ToTable("directors", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EditionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("edition_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_id");

                    b.HasKey("Id")
                        .HasName("pk_editions");

                    b.HasIndex("PublisherId")
                        .HasDatabaseName("ix_editions_publisher_id");

                    b.ToTable("editions", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Editor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id")
                        .HasName("pk_editors");

                    b.ToTable("editors", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.EMaterialFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcademicJournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_journal_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<double>("FileSizeMB")
                        .HasColumnType("double precision")
                        .HasColumnName("file_size_mb");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_e_material_files");

                    b.HasIndex("AcademicJournalId")
                        .HasDatabaseName("ix_e_material_files_academic_journal_id");

                    b.ToTable("e_material_files", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.GraphicDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id")
                        .HasName("pk_graphic_design");

                    b.ToTable("graphic_design", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.GraphicDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id")
                        .HasName("pk_graphic_directors");

                    b.ToTable("graphic_directors", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Interpreters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.Property<string>("WhichToLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("which_to_language");

                    b.HasKey("Id")
                        .HasName("pk_interpreters");

                    b.ToTable("interpreters", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_name");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<Guid>("CommunicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("communication_id");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_destroyed");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("library_name");

                    b.Property<byte>("LibraryType")
                        .HasColumnType("smallint")
                        .HasColumnName("library_type");

                    b.HasKey("Id")
                        .HasName("pk_libraries");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_libraries_address_id");

                    b.HasIndex("CommunicationId")
                        .HasDatabaseName("ix_libraries_communication_id");

                    b.ToTable("libraries", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.OtherPeople", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NamePreAttachment")
                        .HasColumnType("text")
                        .HasColumnName("name_pre_attachment");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_other_peoples");

                    b.ToTable("other_peoples", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcademicJournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_journal_id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<Guid>("CommunicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("communication_id");

                    b.Property<DateTime>("DateOfPublication")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_publication");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_publishers");

                    b.HasIndex("AcademicJournalId")
                        .HasDatabaseName("ix_publishers_academic_journal_id");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_publishers_address_id");

                    b.HasIndex("CommunicationId")
                        .HasDatabaseName("ix_publishers_communication_id");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Redaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id")
                        .HasName("pk_redactions");

                    b.ToTable("redactions", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Researcher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NamePreAttachment")
                        .HasColumnType("text")
                        .HasColumnName("name_pre_attachment");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialty");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.HasKey("Id")
                        .HasName("pk_researchers");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_researchers_university_id");

                    b.ToTable("researchers", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.TechnicalNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Barcode")
                        .HasColumnType("bigint")
                        .HasColumnName("barcode");

                    b.Property<string>("CertificateCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("certificate_code");

                    b.Property<decimal>("ISBN")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("isbn");

                    b.Property<decimal?>("ISSN")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("issn");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_technical_numbers");

                    b.ToTable("technical_numbers", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.TechnicalPlaceholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcademicJournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_journal_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<string>("StockCode")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("stock_code");

                    b.Property<decimal>("StockNumber")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("stock_number");

                    b.Property<string>("WhereIsMaterial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("where_is_material");

                    b.HasKey("Id")
                        .HasName("pk_technical_placeholders");

                    b.HasIndex("AcademicJournalId")
                        .HasDatabaseName("ix_technical_placeholders_academic_journal_id");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_technical_placeholders_library_id");

                    b.ToTable("technical_placeholders", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institute");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("university_name");

                    b.HasKey("Id")
                        .HasName("pk_universities");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_universities_address_id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_universities_branch_id");

                    b.ToTable("universities", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Writer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NamePreAttachment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_pre_attachment");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id")
                        .HasName("pk_writers");

                    b.ToTable("writers", (string)null);
                });

            modelBuilder.Entity("AcademicJournalEditor", b =>
                {
                    b.HasOne("Entities.Concrete.AcademicJournal", null)
                        .WithMany()
                        .HasForeignKey("AcademicJournalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academic_journal_editor_academic_journals_academic_journals");

                    b.HasOne("Entities.Concrete.Infos.Editor", null)
                        .WithMany()
                        .HasForeignKey("EditorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academic_journal_editor_editors_editors_id");
                });

            modelBuilder.Entity("AcademicJournalResearcher", b =>
                {
                    b.HasOne("Entities.Concrete.AcademicJournal", null)
                        .WithMany()
                        .HasForeignKey("AcademicJournalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academic_journal_researcher_academic_journals_academic_jour");

                    b.HasOne("Entities.Concrete.Infos.Researcher", null)
                        .WithMany()
                        .HasForeignKey("ResearchersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academic_journal_researcher_researchers_researchers_id");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Address", b =>
                {
                    b.HasOne("Entities.Concrete.Infos.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_cities_city_id");

                    b.HasOne("Entities.Concrete.Infos.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_countries_country_id");

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Category", b =>
                {
                    b.HasOne("Entities.Concrete.AcademicJournal", null)
                        .WithMany("Categories")
                        .HasForeignKey("AcademicJournalId")
                        .HasConstraintName("fk_categories_academic_journals_academic_journal_id");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Dimension", b =>
                {
                    b.HasOne("Entities.Concrete.AcademicJournal", null)
                        .WithMany("Dimensions")
                        .HasForeignKey("AcademicJournalId")
                        .HasConstraintName("fk_dimensions_academic_journals_academic_journal_id");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Edition", b =>
                {
                    b.HasOne("Entities.Concrete.Infos.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_editions_publishers_publisher_id");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.EMaterialFile", b =>
                {
                    b.HasOne("Entities.Concrete.AcademicJournal", null)
                        .WithMany("EMaterialFiles")
                        .HasForeignKey("AcademicJournalId")
                        .HasConstraintName("fk_e_material_files_academic_journals_academic_journal_id");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Library", b =>
                {
                    b.HasOne("Entities.Concrete.Infos.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_libraries_addresses_address_id");

                    b.HasOne("Entities.Concrete.Infos.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_libraries_communications_communication_id");

                    b.Navigation("Address");

                    b.Navigation("Communication");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Publisher", b =>
                {
                    b.HasOne("Entities.Concrete.AcademicJournal", null)
                        .WithMany("Publishers")
                        .HasForeignKey("AcademicJournalId")
                        .HasConstraintName("fk_publishers_academic_journals_academic_journal_id");

                    b.HasOne("Entities.Concrete.Infos.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publishers_addresses_address_id");

                    b.HasOne("Entities.Concrete.Infos.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publishers_communications_communication_id");

                    b.Navigation("Address");

                    b.Navigation("Communication");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.Researcher", b =>
                {
                    b.HasOne("Entities.Concrete.Infos.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .HasConstraintName("fk_researchers_universities_university_id");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.TechnicalPlaceholder", b =>
                {
                    b.HasOne("Entities.Concrete.AcademicJournal", null)
                        .WithMany("TechnicalPlaceholders")
                        .HasForeignKey("AcademicJournalId")
                        .HasConstraintName("fk_technical_placeholders_academic_journals_academic_journal_id");

                    b.HasOne("Entities.Concrete.Infos.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_technical_placeholders_libraries_library_id");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Entities.Concrete.Infos.University", b =>
                {
                    b.HasOne("Entities.Concrete.Infos.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_universities_addresses_address_id");

                    b.HasOne("Entities.Concrete.Infos.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_universities_branches_branch_id");

                    b.Navigation("Address");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Entities.Concrete.AcademicJournal", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Dimensions");

                    b.Navigation("EMaterialFiles");

                    b.Navigation("Publishers");

                    b.Navigation("TechnicalPlaceholders");
                });
#pragma warning restore 612, 618
        }
    }
}
